from __future__ import annotations

from dataclasses import dataclass

RECOMMENDATIONS_ES_REPLACEMENTS = {
    "Invalid video file": "Archivo de video inválido",
    "WHAT THIS VIDEO HAS": "LO QUE TIENE ESTE VIDEO",
    "RECOMMENDED NEXT STEP": "QUE TE CONVIENE HACER",
    "Short video (0-10s) - Perfect for UI animations or button effects": "Video corto (0-10s) - Perfecto para animaciones de UI o efectos de botones",
    "Use 'Ideal Loop' for videos that need to repeat smoothly": "Usa 'Ideal Loop' para videos que deben repetirse de forma fluida",
    "Increase to 30 FPS for smoother UI animations": "Sube a 30 FPS para animaciones de UI más fluidas",
    "Medium video (10-30s) - Ideal for character animations or environmental loops": "Video medio (10-30s) - Ideal para animaciones de personajes o bucles de entorno",
    "Try 'Official Godot' as the recommended starting point": "Prueba 'Official Godot' como punto de partida recomendado",
    "Long video (30-60s) - Great for cutscenes or character intros": "Video largo (30-60s) - Excelente para cinemáticas o intros de personajes",
    "Use 'High Compression' if you want a smaller file and do not need fast jumps": "Usa 'High Compression' si quieres un archivo más pequeño y no necesitas saltos rápidos",
    "Extended video (60-180s) - Suitable for intro cinematics or tutorials": "Video extendido (60-180s) - Adecuado para cinemáticas introductorias o tutoriales",
    "Split into shorter clips for faster loading in Godot": "Divide en clips más cortos para cargar más rápido en Godot",
    "Use 'Mobile Optimized' for more stable playback on weaker devices": "Usa 'Mobile Optimized' para una reproducción más estable en equipos modestos",
    "Very long video (180s+) - May impact loading times": "Video muy largo (180s+) - Puede afectar los tiempos de carga",
    "Large files possible with OGV; reduce resolution or FPS": "Con OGV pueden generarse archivos grandes; reduce resolución o FPS",
    "Split into smaller clips or stream externally": "Divide en clips más pequeños o reprodúcelos externamente",
    "High resolution detected": "Resolución alta detectada",
    "Large files possible with OGV; try 1080p or 720p to save space": "Con OGV pueden generarse archivos grandes; prueba 1080p o 720p para ahorrar espacio",
    "High-res is fine for short splash screens or cutscenes": "Alta resolución va bien para pantallas splash o cinemáticas cortas",
    "Use 1080p for most Godot projects, or 720p for mobiles": "Usa 1080p para la mayoría de proyectos Godot, o 720p para móviles",
    "Low resolution - Great for mobile or retro-style games": "Baja resolución - Excelente para móviles o juegos estilo retro",
    "Use 'Mobile Optimized' for more predictable playback": "Usa 'Mobile Optimized' para una reproducción más predecible",
    "Standard resolution - Suitable for most Godot projects": "Resolución estándar - Adecuada para la mayoría de proyectos Godot",
    "Try 720p for mobiles or 1080p for desktop": "Prueba 720p para móviles o 1080p para escritorio",
    "High FPS short clip - Great for smooth UI effects": "Clip corto con FPS altos - Excelente para efectos fluidos de UI",
    "High FPS detected": "FPS altos detectados",
    "Reduce to 30 FPS to save space with OGV": "Reduce a 30 FPS para ahorrar espacio con OGV",
    "Low FPS detected": "FPS bajos detectados",
    "Use 24-30 FPS for smooth cinematics or gameplay": "Usa 24-30 FPS para cinemáticas o gameplay más fluidos",
    "24-30 FPS is ideal for OGV in Godot - balances smoothness and size": "24-30 FPS es ideal para OGV en Godot: equilibra fluidez y tamaño",
    "Short video with audio (0-5s) - Perfect for UI sounds or effects": "Video corto con audio (0-5s) - Perfecto para sonidos o efectos de UI",
    "Long video with audio - Great for cutscenes": "Video largo con audio - Excelente para cinemáticas",
    "Extract audio as OGG for better control in Godot": "Extrae el audio como OGG para mejor control en Godot",
    "Audio included - Good for character dialogues or ambient scenes": "Audio incluido - Bueno para diálogos de personajes o escenas ambientales",
    "Consider extracting audio as OGG for flexible control in Godot": "Considera extraer el audio como OGG para un control más flexible en Godot",
    "Audio will be removed because keep_audio is disabled": "El audio será removido porque keep_audio está desactivado",
    "No audio - Ideal for background loops or visual effects": "Sin audio - Ideal para bucles de fondo o efectos visuales",
    "Use OGV for best compatibility in Godot": "Usa OGV para mejor compatibilidad en Godot",
    "Source video codec: unknown": "Códec de video de origen: desconocido",
    "Source audio codec: unknown": "Códec de audio de origen: desconocido",
    "Widescreen (16:9) - Easy fit for fullscreen scenes and cutscenes": "Panorámico (16:9) - Se adapta fácilmente a escenas a pantalla completa y cinemáticas",
    "Classic 4:3 - Useful for retro presentation or stylized UI": "Clásico 4:3 - Útil para una presentación retro o una UI estilizada",
    "Square (1:1) - Useful for UI, icons, or centered loops": "Cuadrado (1:1) - Útil para UI, iconos o bucles centrados",
    "Ultra-wide (21:9) - May need letterboxing or careful layout": "Ultra panorámico (21:9) - Puede necesitar bandas o una composición cuidada",
    "Non-standard aspect ratio - May need cropping, padding, or a custom layout": "Relación de aspecto no estándar - Puede necesitar recorte, relleno o una composición personalizada",
    "MP4 output selected. This is fine for general use, but OGV is recommended for Godot runtime compatibility": "Salida MP4 seleccionada. Sirve para uso general, pero se recomienda OGV para compatibilidad de ejecución en Godot",
    "WebM output selected. This is fine for general use, but OGV is recommended for Godot runtime compatibility": "Salida WebM seleccionada. Sirve para uso general, pero se recomienda OGV para compatibilidad de ejecución en Godot",
    "GIF output selected. Useful for previews/UI loops, but OGV is recommended for in-game video playback in Godot": "Salida GIF seleccionada. Útil para previews/bucles de UI, pero se recomienda OGV para reproducción de video dentro del juego en Godot",
    "OGV is the format natively supported by Godot": "OGV es el formato soportado de forma nativa por Godot",
    "Video looks good for Godot. Use OGV for best compatibility.": "El video se ve bien para Godot. Usa OGV para mejor compatibilidad.",
    "Use 'Seek Friendly' if the video needs to start from different points": "Usa 'Seek Friendly' si el video necesita empezar desde distintos puntos",
    "You may not need to reconvert unless you want a different size or preset": "Puede que no necesites reconvertirlo salvo que quieras otro tamaño o preset",
    "H.264/AVC sources usually convert cleanly to Godot-oriented OGV": "Las fuentes H.264/AVC suelen convertirse bien a OGV orientado a Godot",
    "WebM sources can work as inputs, but OGV is the safer final target for Godot": "Las fuentes WebM pueden usarse como entrada, pero OGV es el destino final más seguro para Godot",
    "Animated GIF sources usually benefit from lower resolution or lower FPS before export": "Las fuentes GIF animadas suelen beneficiarse de una menor resolución o menos FPS antes de exportar",
    "Short video (0-10s) - Good for loops, UI effects, or stylized inserts": "Video corto (0-10s) - Bueno para bucles, efectos de UI o inserts estilizados",
    "Medium video (10-60s) - Suitable for in-game scenes or animated screens": "Video medio (10-60s) - Adecuado para escenas dentro del juego o pantallas animadas",
    "Long video (60s+) - Test playback early on target hardware": "Video largo (60s+) - Prueba la reproducción temprano en el hardware objetivo",
    "Long videos are easier to manage when split into shorter scenes": "Los videos largos se manejan mejor si se dividen en escenas más cortas",
    "Prefer 1080p or 720p unless the game really needs a larger source": "Prefiere 1080p o 720p salvo que el juego realmente necesite una fuente mayor",
    "Low resolution - Good fit for lightweight 2D projects": "Resolución baja - Buena opción para proyectos 2D livianos",
    "Standard resolution - Good baseline for Love2D playback": "Resolución estándar - Buena base para reproducción en Love2D",
    "Reduce to 24-30 FPS if you want a lighter OGV for Love2D": "Reduce a 24-30 FPS si quieres un OGV más liviano para Love2D",
    "Very low FPS may look choppy; 24-30 FPS is a safer default": "Un FPS muy bajo puede verse entrecortado; 24-30 FPS es un valor más seguro",
    "24-30 FPS is a practical target for Love2D video playback": "24-30 FPS es un objetivo práctico para reproducción de video en Love2D",
    "Embedded audio is supported, but test sync and volume on target platforms": "El audio embebido está soportado, pero prueba sincronización y volumen en las plataformas objetivo",
    "No audio - Good for decorative loops or background motion": "Sin audio - Bueno para bucles decorativos o movimiento de fondo",
    "MP4 output selected. Keep OGV for the final Love2D playback path": "Salida MP4 seleccionada. Mantén OGV para la ruta final de reproducción en Love2D",
    "WebM output selected. Keep OGV for the final Love2D playback path": "Salida WebM seleccionada. Mantén OGV para la ruta final de reproducción en Love2D",
    "GIF output selected. Fine for previews, but not as a Love2D video replacement": "Salida GIF seleccionada. Sirve para previews, pero no como reemplazo de video en Love2D",
    "OGV is the main engine-oriented target for Love2D video playback": "OGV es el objetivo principal orientado al motor para reproducción de video en Love2D",
    "If a file fails in Love2D, try 'Love2D Compatibility' first": "Si un archivo falla en Love2D, prueba primero 'Love2D Compatibility'",
    "Use 'Ideal Loop' for videos that need to repeat smoothly": "Usa 'Ideal Loop' para videos que deben repetirse de forma fluida",
    "Use 'Lightweight' if you want a smaller file": "Usa 'Lightweight' si quieres un archivo más pequeño",
    "You may not need to reconvert unless you want a smaller file or a different preset": "Puede que no necesites reconvertirlo salvo que quieras un archivo más pequeño o un preset distinto",
    "H.264/AVC sources are a practical starting point before converting to OGV": "Las fuentes H.264/AVC son un punto de partida práctico antes de convertir a OGV",
    "WebM sources are fine as inputs, but OGV is the safer final target for Love2D": "Las fuentes WebM sirven como entrada, pero OGV es el destino final más seguro para Love2D",
    "Video looks good for Love2D. Use OGV for best compatibility.": "El video se ve bien para Love2D. Usa OGV para mejor compatibilidad.",
}

RECOMMENDATIONS_FR_REPLACEMENTS = {
    "Invalid video file": "Fichier vidéo invalide",
    "WHAT THIS VIDEO HAS": "CE QUE CETTE VIDEO CONTIENT",
    "RECOMMENDED NEXT STEP": "ÉTAPE SUIVANTE RECOMMANDÉE",
    "Short video (0-10s) - Perfect for UI animations or button effects": "Vidéo courte (0-10s) - Parfaite pour les animations d'interface ou les effets de boutons",
    "Use 'Ideal Loop' for videos that need to repeat smoothly": "Utilisez 'Ideal Loop' pour les vidéos qui doivent se répéter en douceur",
    "Increase to 30 FPS for smoother UI animations": "Passez à 30 FPS pour des animations d'interface plus fluides",
    "Medium video (10-30s) - Ideal for character animations or environmental loops": "Vidéo moyenne (10-30s) - Idéale pour les animations de personnages ou les boucles d'environnement",
    "Try 'Official Godot' as the recommended starting point": "Essayez 'Official Godot' comme point de départ recommandé",
    "Long video (30-60s) - Great for cutscenes or character intros": "Vidéo longue (30-60s) - Très adaptée aux cinématiques ou aux introductions de personnages",
    "Use 'High Compression' if you want a smaller file and do not need fast jumps": "Utilisez 'High Compression' si vous voulez un fichier plus petit et n'avez pas besoin de sauts rapides",
    "Extended video (60-180s) - Suitable for intro cinematics or tutorials": "Vidéo étendue (60-180s) - Adaptée aux cinématiques d'introduction ou aux tutoriels",
    "Split into shorter clips for faster loading in Godot": "Découpez en clips plus courts pour un chargement plus rapide dans Godot",
    "Use 'Mobile Optimized' for more stable playback on weaker devices": "Utilisez 'Mobile Optimized' pour une lecture plus stable sur des appareils modestes",
    "Very long video (180s+) - May impact loading times": "Très longue vidéo (180s+) - Peut affecter les temps de chargement",
    "Large files possible with OGV; reduce resolution or FPS": "Avec OGV, les fichiers peuvent être volumineux ; réduisez la résolution ou les FPS",
    "Split into smaller clips or stream externally": "Découpez en clips plus petits ou lisez la vidéo en externe",
    "High resolution detected": "Haute résolution détectée",
    "Large files possible with OGV; try 1080p or 720p to save space": "Avec OGV, les fichiers peuvent être volumineux ; essayez 1080p ou 720p pour gagner de la place",
    "High-res is fine for short splash screens or cutscenes": "Une haute résolution convient bien aux écrans splash courts ou aux cinématiques",
    "Use 1080p for most Godot projects, or 720p for mobiles": "Utilisez 1080p pour la plupart des projets Godot, ou 720p pour les mobiles",
    "Low resolution - Great for mobile or retro-style games": "Basse résolution - Très adaptée aux jeux mobiles ou au style rétro",
    "Use 'Mobile Optimized' for more predictable playback": "Utilisez 'Mobile Optimized' pour une lecture plus prévisible",
    "Standard resolution - Suitable for most Godot projects": "Résolution standard - Adaptée à la plupart des projets Godot",
    "Try 720p for mobiles or 1080p for desktop": "Essayez 720p pour le mobile ou 1080p pour le bureau",
    "High FPS short clip - Great for smooth UI effects": "Clip court à FPS élevés - Idéal pour des effets d'interface fluides",
    "High FPS detected": "FPS élevés détectés",
    "Reduce to 30 FPS to save space with OGV": "Réduisez à 30 FPS pour économiser de l'espace avec OGV",
    "Low FPS detected": "FPS faibles détectés",
    "Use 24-30 FPS for smooth cinematics or gameplay": "Utilisez 24-30 FPS pour des cinématiques ou un gameplay fluide",
    "24-30 FPS is ideal for OGV in Godot - balances smoothness and size": "24-30 FPS est idéal pour OGV dans Godot - bon équilibre entre fluidité et taille",
    "Short video with audio (0-5s) - Perfect for UI sounds or effects": "Vidéo courte avec audio (0-5s) - Parfaite pour les sons ou effets d'interface",
    "Long video with audio - Great for cutscenes": "Vidéo longue avec audio - Très adaptée aux cinématiques",
    "Extract audio as OGG for better control in Godot": "Extrayez l'audio en OGG pour un meilleur contrôle dans Godot",
    "Audio included - Good for character dialogues or ambient scenes": "Audio inclus - Bien adapté aux dialogues de personnages ou aux scènes d'ambiance",
    "Consider extracting audio as OGG for flexible control in Godot": "Pensez à extraire l'audio en OGG pour un contrôle plus souple dans Godot",
    "Audio will be removed because keep_audio is disabled": "L'audio sera supprimé car l'option de conservation est désactivée",
    "No audio - Ideal for background loops or visual effects": "Pas d'audio - Idéal pour les boucles d'arrière-plan ou les effets visuels",
    "Use OGV for best compatibility in Godot": "Utilisez OGV pour la meilleure compatibilité dans Godot",
    "Source video codec: unknown": "Codec vidéo source : inconnu",
    "Source audio codec: unknown": "Codec audio source : inconnu",
    "Widescreen (16:9) - Easy fit for fullscreen scenes and cutscenes": "Format large (16:9) - S'adapte facilement aux scènes plein écran et aux cinématiques",
    "Classic 4:3 - Useful for retro presentation or stylized UI": "Format classique 4:3 - Utile pour une présentation rétro ou une interface stylisée",
    "Square (1:1) - Useful for UI, icons, or centered loops": "Format carré (1:1) - Utile pour l'interface, les icônes ou les boucles centrées",
    "Ultra-wide (21:9) - May need letterboxing or careful layout": "Ultra-large (21:9) - Peut nécessiter des bandes noires ou une mise en page soignée",
    "Non-standard aspect ratio - May need cropping, padding, or a custom layout": "Format non standard - Peut nécessiter un recadrage, des marges ou une mise en page personnalisée",
    "MP4 output selected. This is fine for general use, but OGV is recommended for Godot runtime compatibility": "Sortie MP4 sélectionnée. C'est correct pour un usage général, mais OGV est recommandé pour la compatibilité d'exécution dans Godot",
    "WebM output selected. This is fine for general use, but OGV is recommended for Godot runtime compatibility": "Sortie WebM sélectionnée. C'est correct pour un usage général, mais OGV est recommandé pour la compatibilité d'exécution dans Godot",
    "GIF output selected. Useful for previews/UI loops, but OGV is recommended for in-game video playback in Godot": "Sortie GIF sélectionnée. Utile pour les aperçus ou les boucles d'interface, mais OGV est recommandé pour la lecture vidéo dans Godot",
    "OGV is the format natively supported by Godot": "OGV est le format pris en charge nativement par Godot",
    "Video looks good for Godot. Use OGV for best compatibility.": "La vidéo semble correcte pour Godot. Utilisez OGV pour une meilleure compatibilité.",
    "Use 'Seek Friendly' if the video needs to start from different points": "Utilisez 'Seek Friendly' si la vidéo doit démarrer depuis différents points",
    "You may not need to reconvert unless you want a different size or preset": "Il n'est peut-être pas nécessaire de reconvertir sauf si vous voulez une autre taille ou un autre preset",
    "H.264/AVC sources usually convert cleanly to Godot-oriented OGV": "Les sources H.264/AVC se convertissent généralement bien vers un OGV orienté Godot",
    "WebM sources can work as inputs, but OGV is the safer final target for Godot": "Les sources WebM peuvent servir d'entrée, mais OGV est la cible finale la plus sûre pour Godot",
    "Animated GIF sources usually benefit from lower resolution or lower FPS before export": "Les sources GIF animées bénéficient souvent d'une résolution ou de FPS plus faibles avant l'export",
    "Short video (0-10s) - Good for loops, UI effects, or stylized inserts": "Vidéo courte (0-10s) - Bien adaptée aux boucles, effets d'interface ou inserts stylisés",
    "Medium video (10-60s) - Suitable for in-game scenes or animated screens": "Vidéo moyenne (10-60s) - Adaptée aux scènes en jeu ou aux écrans animés",
    "Long video (60s+) - Test playback early on target hardware": "Vidéo longue (60s+) - Testez la lecture tôt sur le matériel cible",
    "Long videos are easier to manage when split into shorter scenes": "Les longues vidéos sont plus faciles à gérer lorsqu'elles sont divisées en scènes plus courtes",
    "Prefer 1080p or 720p unless the game really needs a larger source": "Préférez 1080p ou 720p sauf si le jeu a vraiment besoin d'une source plus grande",
    "Low resolution - Good fit for lightweight 2D projects": "Basse résolution - Bien adaptée aux projets 2D légers",
    "Standard resolution - Good baseline for Love2D playback": "Résolution standard - Bonne base pour la lecture dans Love2D",
    "Reduce to 24-30 FPS if you want a lighter OGV for Love2D": "Réduisez à 24-30 FPS si vous voulez un OGV plus léger pour Love2D",
    "Very low FPS may look choppy; 24-30 FPS is a safer default": "Des FPS très faibles peuvent sembler saccadés ; 24-30 FPS est une valeur plus sûre",
    "24-30 FPS is a practical target for Love2D video playback": "24-30 FPS est une cible pratique pour la lecture vidéo dans Love2D",
    "Embedded audio is supported, but test sync and volume on target platforms": "L'audio intégré est pris en charge, mais testez la synchronisation et le volume sur les plateformes cibles",
    "No audio - Good for decorative loops or background motion": "Pas d'audio - Bien adapté aux boucles décoratives ou aux mouvements d'arrière-plan",
    "MP4 output selected. Keep OGV for the final Love2D playback path": "Sortie MP4 sélectionnée. Gardez OGV pour la lecture finale dans Love2D",
    "WebM output selected. Keep OGV for the final Love2D playback path": "Sortie WebM sélectionnée. Gardez OGV pour la lecture finale dans Love2D",
    "GIF output selected. Fine for previews, but not as a Love2D video replacement": "Sortie GIF sélectionnée. Correcte pour les aperçus, mais pas comme remplacement vidéo dans Love2D",
    "OGV is the main engine-oriented target for Love2D video playback": "OGV est la principale cible orientée moteur pour la lecture vidéo dans Love2D",
    "If a file fails in Love2D, try 'Love2D Compatibility' first": "Si un fichier échoue dans Love2D, essayez d'abord 'Love2D Compatibility'",
    "Use 'Lightweight' if you want a smaller file": "Utilisez 'Lightweight' si vous voulez un fichier plus petit",
    "You may not need to reconvert unless you want a smaller file or a different preset": "Il n'est peut-être pas nécessaire de reconvertir sauf si vous voulez un fichier plus petit ou un preset différent",
    "H.264/AVC sources are a practical starting point before converting to OGV": "Les sources H.264/AVC constituent un point de départ pratique avant la conversion en OGV",
    "WebM sources are fine as inputs, but OGV is the safer final target for Love2D": "Les sources WebM conviennent en entrée, mais OGV reste la cible finale la plus sûre pour Love2D",
    "Video looks good for Love2D. Use OGV for best compatibility.": "La vidéo semble correcte pour Love2D. Utilisez OGV pour une meilleure compatibilité.",
}

RECOMMENDATIONS_DE_REPLACEMENTS = {
    "Invalid video file": "Ungültige Videodatei",
    "WHAT THIS VIDEO HAS": "WAS DIESES VIDEO HAT",
    "RECOMMENDED NEXT STEP": "EMPFOHLENER NÄCHSTER SCHRITT",
    "Short video (0-10s) - Perfect for UI animations or button effects": "Kurzes Video (0-10s) - Ideal für UI-Animationen oder Schaltflächeneffekte",
    "Use 'Ideal Loop' for videos that need to repeat smoothly": "Verwende 'Ideal Loop' für Videos, die flüssig wiederholt werden sollen",
    "Increase to 30 FPS for smoother UI animations": "Erhöhe auf 30 FPS für flüssigere UI-Animationen",
    "Medium video (10-30s) - Ideal for character animations or environmental loops": "Mittellanges Video (10-30s) - Ideal für Charakteranimationen oder Umgebungsloops",
    "Try 'Official Godot' as the recommended starting point": "Versuche 'Official Godot' als empfohlenen Ausgangspunkt",
    "Long video (30-60s) - Great for cutscenes or character intros": "Langes Video (30-60s) - Gut geeignet für Zwischensequenzen oder Charakter-Intros",
    "Use 'High Compression' if you want a smaller file and do not need fast jumps": "Verwende 'High Compression', wenn du eine kleinere Datei willst und keine schnellen Sprünge brauchst",
    "Extended video (60-180s) - Suitable for intro cinematics or tutorials": "Längeres Video (60-180s) - Geeignet für Intro-Cinematics oder Tutorials",
    "Split into shorter clips for faster loading in Godot": "Teile es in kürzere Clips für schnelleres Laden in Godot",
    "Use 'Mobile Optimized' for more stable playback on weaker devices": "Verwende 'Mobile Optimized' für stabilere Wiedergabe auf schwächeren Geräten",
    "Very long video (180s+) - May impact loading times": "Sehr langes Video (180s+) - Kann die Ladezeiten beeinflussen",
    "Large files possible with OGV; reduce resolution or FPS": "Mit OGV sind große Dateien möglich; reduziere Auflösung oder FPS",
    "Split into smaller clips or stream externally": "Teile es in kleinere Clips oder streame es extern",
    "High resolution detected": "Hohe Auflösung erkannt",
    "Large files possible with OGV; try 1080p or 720p to save space": "Mit OGV sind große Dateien möglich; versuche 1080p oder 720p, um Platz zu sparen",
    "High-res is fine for short splash screens or cutscenes": "Hohe Auflösung ist für kurze Splash-Screens oder Zwischensequenzen in Ordnung",
    "Use 1080p for most Godot projects, or 720p for mobiles": "Verwende 1080p für die meisten Godot-Projekte oder 720p für Mobilgeräte",
    "Low resolution - Great for mobile or retro-style games": "Niedrige Auflösung - Gut für Mobil- oder Retro-Spiele",
    "Use 'Mobile Optimized' for more predictable playback": "Verwende 'Mobile Optimized' für besser vorhersehbare Wiedergabe",
    "Standard resolution - Suitable for most Godot projects": "Standardauflösung - Für die meisten Godot-Projekte geeignet",
    "Try 720p for mobiles or 1080p for desktop": "Versuche 720p für Mobilgeräte oder 1080p für Desktop",
    "High FPS short clip - Great for smooth UI effects": "Kurzer Clip mit hohen FPS - Ideal für flüssige UI-Effekte",
    "High FPS detected": "Hohe FPS erkannt",
    "Reduce to 30 FPS to save space with OGV": "Reduziere auf 30 FPS, um mit OGV Platz zu sparen",
    "Low FPS detected": "Niedrige FPS erkannt",
    "Use 24-30 FPS for smooth cinematics or gameplay": "Verwende 24-30 FPS für flüssige Zwischensequenzen oder Gameplay",
    "24-30 FPS is ideal for OGV in Godot - balances smoothness and size": "24-30 FPS sind ideal für OGV in Godot - guter Ausgleich zwischen Flüssigkeit und Dateigröße",
    "Short video with audio (0-5s) - Perfect for UI sounds or effects": "Kurzes Video mit Audio (0-5s) - Ideal für UI-Sounds oder Effekte",
    "Long video with audio - Great for cutscenes": "Langes Video mit Audio - Gut geeignet für Zwischensequenzen",
    "Extract audio as OGG for better control in Godot": "Extrahiere Audio als OGG für bessere Kontrolle in Godot",
    "Audio included - Good for character dialogues or ambient scenes": "Audio enthalten - Gut für Charakterdialoge oder stimmungsvolle Szenen",
    "Consider extracting audio as OGG for flexible control in Godot": "Erwäge, Audio als OGG zu extrahieren, um es in Godot flexibler zu steuern",
    "Audio will be removed because keep_audio is disabled": "Audio wird entfernt, weil 'Audio beibehalten' deaktiviert ist",
    "No audio - Ideal for background loops or visual effects": "Kein Audio - Ideal für Hintergrundloops oder visuelle Effekte",
    "Use OGV for best compatibility in Godot": "Verwende OGV für die beste Kompatibilität in Godot",
    "Source video codec: unknown": "Quell-Videocodec: unbekannt",
    "Source audio codec: unknown": "Quell-Audiocodec: unbekannt",
    "Widescreen (16:9) - Easy fit for fullscreen scenes and cutscenes": "Breitbild (16:9) - Passt gut zu Vollbildszenen und Zwischensequenzen",
    "Classic 4:3 - Useful for retro presentation or stylized UI": "Klassisches 4:3 - Nützlich für Retro-Präsentation oder stilisierte UI",
    "Square (1:1) - Useful for UI, icons, or centered loops": "Quadratisch (1:1) - Nützlich für UI, Icons oder zentrierte Loops",
    "Ultra-wide (21:9) - May need letterboxing or careful layout": "Ultra-Breitbild (21:9) - Kann Letterboxing oder ein sorgfältiges Layout brauchen",
    "Non-standard aspect ratio - May need cropping, padding, or a custom layout": "Ungewöhnliches Seitenverhältnis - Kann Zuschnitt, Padding oder ein eigenes Layout erfordern",
    "MP4 output selected. This is fine for general use, but OGV is recommended for Godot runtime compatibility": "MP4-Ausgabe gewählt. Für allgemeinen Gebrauch ist das in Ordnung, aber OGV wird für die Laufzeitkompatibilität in Godot empfohlen",
    "WebM output selected. This is fine for general use, but OGV is recommended for Godot runtime compatibility": "WebM-Ausgabe gewählt. Für allgemeinen Gebrauch ist das in Ordnung, aber OGV wird für die Laufzeitkompatibilität in Godot empfohlen",
    "GIF output selected. Useful for previews/UI loops, but OGV is recommended for in-game video playback in Godot": "GIF-Ausgabe gewählt. Nützlich für Vorschauen oder UI-Loops, aber OGV wird für Ingame-Videowiedergabe in Godot empfohlen",
    "OGV is the format natively supported by Godot": "OGV ist das von Godot nativ unterstützte Format",
    "Video looks good for Godot. Use OGV for best compatibility.": "Das Video sieht für Godot gut aus. Verwende OGV für die beste Kompatibilität.",
    "Use 'Seek Friendly' if the video needs to start from different points": "Verwende 'Seek Friendly', wenn das Video von verschiedenen Punkten starten soll",
    "You may not need to reconvert unless you want a different size or preset": "Du musst es möglicherweise nicht neu konvertieren, außer du möchtest eine andere Größe oder ein anderes Preset",
    "H.264/AVC sources usually convert cleanly to Godot-oriented OGV": "H.264/AVC-Quellen lassen sich meist sauber in Godot-orientiertes OGV umwandeln",
    "WebM sources can work as inputs, but OGV is the safer final target for Godot": "WebM-Quellen funktionieren als Eingabe, aber OGV ist das sicherere endgültige Zielformat für Godot",
    "Animated GIF sources usually benefit from lower resolution or lower FPS before export": "Animierte GIF-Quellen profitieren meist von geringerer Auflösung oder weniger FPS vor dem Export",
    "Short video (0-10s) - Good for loops, UI effects, or stylized inserts": "Kurzes Video (0-10s) - Gut für Loops, UI-Effekte oder stilisierte Einblendungen",
    "Medium video (10-60s) - Suitable for in-game scenes or animated screens": "Mittellanges Video (10-60s) - Geeignet für Spielszenen oder animierte Bildschirme",
    "Long video (60s+) - Test playback early on target hardware": "Langes Video (60s+) - Teste die Wiedergabe früh auf der Zielhardware",
    "Long videos are easier to manage when split into shorter scenes": "Lange Videos lassen sich leichter verwalten, wenn sie in kürzere Szenen aufgeteilt werden",
    "Prefer 1080p or 720p unless the game really needs a larger source": "Bevorzuge 1080p oder 720p, außer das Spiel braucht wirklich eine größere Quelle",
    "Low resolution - Good fit for lightweight 2D projects": "Niedrige Auflösung - Gut geeignet für leichte 2D-Projekte",
    "Standard resolution - Good baseline for Love2D playback": "Standardauflösung - Gute Basis für die Wiedergabe in Love2D",
    "Reduce to 24-30 FPS if you want a lighter OGV for Love2D": "Reduziere auf 24-30 FPS, wenn du ein leichteres OGV für Love2D möchtest",
    "Very low FPS may look choppy; 24-30 FPS is a safer default": "Sehr niedrige FPS können ruckelig wirken; 24-30 FPS sind ein sicherer Standard",
    "24-30 FPS is a practical target for Love2D video playback": "24-30 FPS sind ein praktikables Ziel für Videowiedergabe in Love2D",
    "Embedded audio is supported, but test sync and volume on target platforms": "Eingebettetes Audio wird unterstützt, aber teste Synchronität und Lautstärke auf den Zielplattformen",
    "No audio - Good for decorative loops or background motion": "Kein Audio - Gut für dekorative Loops oder Hintergrundbewegung",
    "MP4 output selected. Keep OGV for the final Love2D playback path": "MP4-Ausgabe gewählt. Nutze OGV für die endgültige Wiedergabe in Love2D",
    "WebM output selected. Keep OGV for the final Love2D playback path": "WebM-Ausgabe gewählt. Nutze OGV für die endgültige Wiedergabe in Love2D",
    "GIF output selected. Fine for previews, but not as a Love2D video replacement": "GIF-Ausgabe gewählt. Gut für Vorschauen, aber kein Ersatz für Video in Love2D",
    "OGV is the main engine-oriented target for Love2D video playback": "OGV ist das wichtigste engine-orientierte Zielformat für Videowiedergabe in Love2D",
    "If a file fails in Love2D, try 'Love2D Compatibility' first": "Wenn eine Datei in Love2D nicht funktioniert, versuche zuerst 'Love2D Compatibility'",
    "Use 'Lightweight' if you want a smaller file": "Verwende 'Lightweight', wenn du eine kleinere Datei möchtest",
    "You may not need to reconvert unless you want a smaller file or a different preset": "Du musst es möglicherweise nicht neu konvertieren, außer du möchtest eine kleinere Datei oder ein anderes Preset",
    "H.264/AVC sources are a practical starting point before converting to OGV": "H.264/AVC-Quellen sind ein praktischer Ausgangspunkt vor der Umwandlung in OGV",
    "WebM sources are fine as inputs, but OGV is the safer final target for Love2D": "WebM-Quellen sind als Eingabe in Ordnung, aber OGV ist das sicherere endgültige Zielformat für Love2D",
    "Video looks good for Love2D. Use OGV for best compatibility.": "Das Video sieht für Love2D gut aus. Verwende OGV für die beste Kompatibilität.",
}

RECOMMENDATIONS_ZH_CN_REPLACEMENTS = {
    "Invalid video file": "无效的视频文件",
    "WHAT THIS VIDEO HAS": "此视频的特点",
    "RECOMMENDED NEXT STEP": "建议的下一步",
    "Short video (0-10s) - Perfect for UI animations or button effects": "短视频（0-10 秒）- 非常适合 UI 动画或按钮效果",
    "Use 'Ideal Loop' for videos that need to repeat smoothly": "对需要平滑重复的视频使用“Ideal Loop”",
    "Use 'Ideal Loop' only when seamless repetition matters more than file size": "仅当无缝循环比文件大小更重要时使用“Ideal Loop”",
    "Increase to 30 FPS for smoother UI animations": "提高到 30 FPS 可获得更流畅的 UI 动画",
    "Medium video (10-30s) - Ideal for character animations or environmental loops": "中等长度视频（10-30 秒）- 适合角色动画或环境循环",
    "Try 'Official Godot' as the recommended starting point": "建议先从“Official Godot”开始",
    "Long video (30-60s) - Great for cutscenes or character intros": "长视频（30-60 秒）- 适合过场动画或角色介绍",
    "Start with 'Official Godot'; use 'High Compression' only if file size matters more than quick seeking": "先使用“Official Godot”；只有当文件大小比快速跳转更重要时才使用“High Compression”",
    "Extended video (60-180s) - Suitable for intro cinematics or tutorials": "较长视频（60-180 秒）- 适合开场过场或教程",
    "Split into shorter clips for faster loading in Godot": "拆分成更短的片段，可在 Godot 中更快加载",
    "Use 'Mobile Optimized' for steadier playback, or 'High Compression' if size is the main concern": "需要更稳定播放时使用“Mobile Optimized”；如果主要关注大小，则使用“High Compression”",
    "Very long video (180s+) - May impact loading times": "超长视频（180 秒以上）- 可能影响加载时间",
    "Large files possible with OGV; reduce resolution or FPS": "OGV 可能生成较大文件；请降低分辨率或 FPS",
    "Split into smaller clips or stream externally": "拆分成更小片段，或在外部流式播放",
    "Avoid 'Ideal Loop' on long videos unless the clip is very short and truly loop-focused": "除非片段很短且确实以循环为核心，否则避免在长视频上使用“Ideal Loop”",
    "High resolution detected": "检测到高分辨率",
    "Large files possible with OGV; try 1080p or 720p to save space": "OGV 可能生成较大文件；可尝试 1080p 或 720p 节省空间",
    "High-res is fine for short splash screens or cutscenes": "高分辨率适合短启动画面或短过场",
    "Use 1080p for most Godot projects, or 720p for mobiles": "多数 Godot 项目可使用 1080p，移动端可使用 720p",
    "Low resolution - Great for mobile or retro-style games": "低分辨率 - 很适合移动端或复古风格游戏",
    "Use 'Mobile Optimized' for more predictable playback": "使用“Mobile Optimized”可获得更可预期的播放效果",
    "Standard resolution - Suitable for most Godot projects": "标准分辨率 - 适合大多数 Godot 项目",
    "Try 720p for mobiles or 1080p for desktop": "移动端可尝试 720p，桌面端可尝试 1080p",
    "High FPS short clip - Great for smooth UI effects": "高 FPS 短片段 - 很适合流畅的 UI 效果",
    "High FPS detected": "检测到高 FPS",
    "Reduce to 30 FPS to save space with OGV": "降低到 30 FPS 可节省 OGV 空间",
    "Low FPS detected": "检测到低 FPS",
    "Use 24-30 FPS for smooth cinematics or gameplay": "使用 24-30 FPS 可获得较流畅的过场或玩法画面",
    "24-30 FPS is ideal for OGV in Godot - balances smoothness and size": "24-30 FPS 适合 Godot 中的 OGV，可平衡流畅度和大小",
    "Short video with audio (0-5s) - Perfect for UI sounds or effects": "带音频的短视频（0-5 秒）- 非常适合 UI 声音或效果",
    "Long video with audio - Great for cutscenes": "带音频的长视频 - 适合过场动画",
    "Extract audio as OGG for better control in Godot": "将音频提取为 OGG，可在 Godot 中更灵活控制",
    "Audio included - Good for character dialogues or ambient scenes": "包含音频 - 适合角色对白或环境场景",
    "Consider extracting audio as OGG for flexible control in Godot": "可考虑将音频提取为 OGG，以便在 Godot 中灵活控制",
    "Audio will be removed because keep_audio is disabled": "由于未启用保留音频，音频将被移除",
    "No audio - Ideal for background loops or visual effects": "无音频 - 适合背景循环或视觉效果",
    "Use OGV for best compatibility in Godot": "在 Godot 中使用 OGV 可获得最佳兼容性",
    "Source video codec: unknown": "源视频编解码器：未知",
    "Source audio codec: unknown": "源音频编解码器：未知",
    "Widescreen (16:9) - Easy fit for fullscreen scenes and cutscenes": "宽屏（16:9）- 容易适配全屏场景和过场",
    "Classic 4:3 - Useful for retro presentation or stylized UI": "经典 4:3 - 适合复古呈现或风格化 UI",
    "Square (1:1) - Useful for UI, icons, or centered loops": "方形（1:1）- 适合 UI、图标或居中循环",
    "Ultra-wide (21:9) - May need letterboxing or careful layout": "超宽屏（21:9）- 可能需要黑边或更仔细的布局",
    "Non-standard aspect ratio - May need cropping, padding, or a custom layout": "非标准宽高比 - 可能需要裁剪、留边或自定义布局",
    "MP4 output selected. This is fine for general use, but OGV is recommended for Godot runtime compatibility": "已选择 MP4 输出。通用用途没问题，但 Godot 运行时兼容性建议使用 OGV",
    "WebM output selected. This is fine for general use, but OGV is recommended for Godot runtime compatibility": "已选择 WebM 输出。通用用途没问题，但 Godot 运行时兼容性建议使用 OGV",
    "GIF output selected. Useful for previews/UI loops, but OGV is recommended for in-game video playback in Godot": "已选择 GIF 输出。适合预览或 UI 循环，但 Godot 游戏内视频播放建议使用 OGV",
    "OGV is the format natively supported by Godot": "OGV 是 Godot 原生支持的格式",
    "Video looks good for Godot. Use OGV for best compatibility.": "此视频适合 Godot。使用 OGV 可获得最佳兼容性。",
    "Use 'Seek Friendly' if the video needs to start from different points": "如果视频需要从不同位置开始，请使用“Seek Friendly”",
    "You may not need to reconvert unless you want a different size or preset": "除非需要不同大小或预设，否则可能不需要重新转换",
    "H.264/AVC sources usually convert cleanly to Godot-oriented OGV": "H.264/AVC 源通常能顺利转换为面向 Godot 的 OGV",
    "WebM sources can work as inputs, but OGV is the safer final target for Godot": "WebM 可作为输入，但 OGV 是 Godot 更稳妥的最终目标",
    "Animated GIF sources usually benefit from lower resolution or lower FPS before export": "动画 GIF 源在导出前通常适合降低分辨率或 FPS",
    "For longer clips, prefer 'Official Godot', 'Mobile Optimized', or 'High Compression' before trying 'Ideal Loop'": "对于较长片段，先考虑“Official Godot”“Mobile Optimized”或“High Compression”，再尝试“Ideal Loop”",
    "Short video (0-10s) - Good for loops, UI effects, or stylized inserts": "短视频（0-10 秒）- 适合循环、UI 效果或风格化插入",
    "Use 'Ideal Loop' only when the clip is short and the repeat must feel seamless": "仅当片段较短且循环必须无缝时使用“Ideal Loop”",
    "Medium video (10-60s) - Suitable for in-game scenes or animated screens": "中等长度视频（10-60 秒）- 适合游戏内场景或动画屏幕",
    "Long video (60s+) - Test playback early on target hardware": "长视频（60 秒以上）- 请尽早在目标硬件上测试播放",
    "Long videos are easier to manage when split into shorter scenes": "将长视频拆成较短场景会更容易管理",
    "Start with 'Love2D Compatibility' or 'Lightweight' before trying more aggressive loop settings": "在尝试更激进的循环设置前，先使用“Love2D Compatibility”或“Lightweight”",
    "Prefer 1080p or 720p unless the game really needs a larger source": "除非游戏确实需要更大源素材，否则优先使用 1080p 或 720p",
    "Low resolution - Good fit for lightweight 2D projects": "低分辨率 - 适合轻量 2D 项目",
    "Standard resolution - Good baseline for Love2D playback": "标准分辨率 - 适合作为 Love2D 播放基线",
    "Reduce to 24-30 FPS if you want a lighter OGV for Love2D": "如果想为 Love2D 获得更轻量的 OGV，请降到 24-30 FPS",
    "Very low FPS may look choppy; 24-30 FPS is a safer default": "非常低的 FPS 可能显得卡顿；24-30 FPS 是更稳妥的默认值",
    "24-30 FPS is a practical target for Love2D video playback": "24-30 FPS 是 Love2D 视频播放的实用目标",
    "Embedded audio is supported, but test sync and volume on target platforms": "支持嵌入音频，但请在目标平台测试同步和音量",
    "No audio - Good for decorative loops or background motion": "无音频 - 适合装饰性循环或背景运动",
    "If a file fails in Love2D, try 'Love2D Compatibility' first": "如果文件在 Love2D 中失败，请先尝试“Love2D Compatibility”",
    "Use 'Lightweight' if you want a smaller file": "如果需要更小文件，请使用“Lightweight”",
    "Avoid 'Ideal Loop' on longer Love2D clips unless the video is a short decorative loop": "除非视频是短装饰循环，否则避免在较长的 Love2D 片段上使用“Ideal Loop”",
    "MP4 output selected. Keep OGV for the final Love2D playback path": "已选择 MP4 输出。最终 Love2D 播放路径请保留 OGV",
    "WebM output selected. Keep OGV for the final Love2D playback path": "已选择 WebM 输出。最终 Love2D 播放路径请保留 OGV",
    "GIF output selected. Fine for previews, but not as a Love2D video replacement": "已选择 GIF 输出。适合预览，但不能替代 Love2D 视频",
    "OGV is the main engine-oriented target for Love2D video playback": "OGV 是 Love2D 视频播放主要的面向引擎目标格式",
    "You may not need to reconvert unless you want a smaller file or a different preset": "除非需要更小文件或不同预设，否则可能不需要重新转换",
    "H.264/AVC sources are a practical starting point before converting to OGV": "H.264/AVC 源是转换为 OGV 前的实用起点",
    "WebM sources are fine as inputs, but OGV is the safer final target for Love2D": "WebM 可作为输入，但 OGV 是 Love2D 更稳妥的最终目标",
    "Video looks good for Love2D. Use OGV for best compatibility.": "此视频适合 Love2D。使用 OGV 可获得最佳兼容性。",
}


@dataclass(frozen=True)
class RecommendationProfile:
    replacements: dict[str, str]
    regex_rules: tuple[tuple[str, str], ...]


_RECOMMENDATION_REGEX_RULES = {
    "de": (
        (r"Source codec \((.+?)\) is already OGV-compatible for Godot", r"Der Quellcodec (\1) ist bereits OGV-kompatibel für Godot"),
        (r"Converting from (.+?) to OGV is recommended for Godot compatibility", r"Die Umwandlung von \1 nach OGV wird für die Kompatibilität mit Godot empfohlen"),
        (r"Source video codec: (.+?) - already in the OGV/Theora family", r"Quell-Videocodec: \1 - bereits in der OGV/Theora-Familie"),
        (r"Source video codec: (.+?) - common source format for exported videos", r"Quell-Videocodec: \1 - gängiges Quellformat für exportierte Videos"),
        (r"Source video codec: (.+?) - web-oriented source video format", r"Quell-Videocodec: \1 - weborientiertes Videoformat"),
        (r"Source video codec: (.+?) - animated image style source", r"Quell-Videocodec: \1 - Quelle im Stil eines animierten Bildes"),
        (r"Source video codec: (.+)", r"Quell-Videocodec: \1"),
        (r"Source audio codec: (.+?) - common in MP4 exports", r"Quell-Audiocodec: \1 - häufig in MP4-Exporten"),
        (r"Source audio codec: (.+?) - already close to OGV workflows", r"Quell-Audiocodec: \1 - bereits nah an OGV-Workflows"),
        (r"Source audio codec: (.+?) - efficient web-oriented audio", r"Quell-Audiocodec: \1 - effizientes weborientiertes Audio"),
        (r"Source audio codec: (.+?) - common compressed audio", r"Quell-Audiocodec: \1 - gängiges komprimiertes Audio"),
        (r"Source audio codec: (.+?) - uncompressed or near-uncompressed audio", r"Quell-Audiocodec: \1 - unkomprimiertes oder nahezu unkomprimiertes Audio"),
        (r"Source audio codec: (.+)", r"Quell-Audiocodec: \1"),
        (r"Source codec \((.+?)\) is already OGV-compatible for Love2D", r"Der Quellcodec (\1) ist bereits OGV-kompatibel für Love2D"),
        (r"Converting from (.+?) to OGV is recommended for Love2D compatibility", r"Die Umwandlung von \1 nach OGV wird für die Kompatibilität mit Love2D empfohlen"),
    ),
    "fr": (
        (r"Source codec \((.+?)\) is already OGV-compatible for Godot", r"Le codec source (\1) est déjà compatible OGV pour Godot"),
        (r"Converting from (.+?) to OGV is recommended for Godot compatibility", r"La conversion de \1 vers OGV est recommandée pour la compatibilité avec Godot"),
        (r"Source video codec: (.+?) - already in the OGV/Theora family", r"Codec vidéo source : \1 - déjà dans la famille OGV/Theora"),
        (r"Source video codec: (.+?) - common source format for exported videos", r"Codec vidéo source : \1 - format source courant pour les vidéos exportées"),
        (r"Source video codec: (.+?) - web-oriented source video format", r"Codec vidéo source : \1 - format vidéo orienté web"),
        (r"Source video codec: (.+?) - animated image style source", r"Codec vidéo source : \1 - source de type image animée"),
        (r"Source video codec: (.+)", r"Codec vidéo source : \1"),
        (r"Source audio codec: (.+?) - common in MP4 exports", r"Codec audio source : \1 - courant dans les exports MP4"),
        (r"Source audio codec: (.+?) - already close to OGV workflows", r"Codec audio source : \1 - déjà proche des flux OGV"),
        (r"Source audio codec: (.+?) - efficient web-oriented audio", r"Codec audio source : \1 - audio efficace orienté web"),
        (r"Source audio codec: (.+?) - common compressed audio", r"Codec audio source : \1 - audio compressé courant"),
        (r"Source audio codec: (.+?) - uncompressed or near-uncompressed audio", r"Codec audio source : \1 - audio non compressé ou presque"),
        (r"Source audio codec: (.+)", r"Codec audio source : \1"),
        (r"Source codec \((.+?)\) is already OGV-compatible for Love2D", r"Le codec source (\1) est déjà compatible OGV pour Love2D"),
        (r"Converting from (.+?) to OGV is recommended for Love2D compatibility", r"La conversion de \1 vers OGV est recommandée pour la compatibilité avec Love2D"),
    ),
    "es": (
        (r"Source codec \((.+?)\) is already OGV-compatible for Godot", r"El códec de origen (\1) ya es compatible con OGV para Godot"),
        (r"Converting from (.+?) to OGV is recommended for Godot compatibility", r"Se recomienda convertir de \1 a OGV para compatibilidad con Godot"),
        (r"Source video codec: (.+?) - already in the OGV/Theora family", r"Códec de video de origen: \1 - ya está en la familia OGV/Theora"),
        (r"Source video codec: (.+?) - common source format for exported videos", r"Códec de video de origen: \1 - formato de origen común en videos exportados"),
        (r"Source video codec: (.+?) - web-oriented source video format", r"Códec de video de origen: \1 - formato de video orientado a web"),
        (r"Source video codec: (.+?) - animated image style source", r"Códec de video de origen: \1 - fuente de estilo imagen animada"),
        (r"Source video codec: (.+)", r"Códec de video de origen: \1"),
        (r"Source audio codec: (.+?) - common in MP4 exports", r"Códec de audio de origen: \1 - común en exportaciones MP4"),
        (r"Source audio codec: (.+?) - already close to OGV workflows", r"Códec de audio de origen: \1 - ya está cerca de los flujos OGV"),
        (r"Source audio codec: (.+?) - efficient web-oriented audio", r"Códec de audio de origen: \1 - audio eficiente orientado a web"),
        (r"Source audio codec: (.+?) - common compressed audio", r"Códec de audio de origen: \1 - audio comprimido común"),
        (r"Source audio codec: (.+?) - uncompressed or near-uncompressed audio", r"Códec de audio de origen: \1 - audio sin comprimir o casi sin comprimir"),
        (r"Source audio codec: (.+)", r"Códec de audio de origen: \1"),
        (r"Source codec \((.+?)\) is already OGV-compatible for Love2D", r"El códec de origen (\1) ya es compatible con OGV para Love2D"),
        (r"Converting from (.+?) to OGV is recommended for Love2D compatibility", r"Se recomienda convertir de \1 a OGV para compatibilidad con Love2D"),
    ),
    "zh_CN": (
        (r"Source codec \((.+?)\) is already OGV-compatible for Godot", r"源编解码器（\1）已兼容 Godot 的 OGV"),
        (r"Converting from (.+?) to OGV is recommended for Godot compatibility", r"为兼容 Godot，建议从 \1 转换为 OGV"),
        (r"Source video codec: (.+?) - already in the OGV/Theora family", r"源视频编解码器：\1 - 已属于 OGV/Theora 系列"),
        (r"Source video codec: (.+?) - common source format for exported videos", r"源视频编解码器：\1 - 导出视频中常见的源格式"),
        (r"Source video codec: (.+?) - web-oriented source video format", r"源视频编解码器：\1 - 面向 Web 的视频格式"),
        (r"Source video codec: (.+?) - animated image style source", r"源视频编解码器：\1 - 动画图像类源文件"),
        (r"Source video codec: (.+)", r"源视频编解码器：\1"),
        (r"Source audio codec: (.+?) - common in MP4 exports", r"源音频编解码器：\1 - MP4 导出中常见"),
        (r"Source audio codec: (.+?) - already close to OGV workflows", r"源音频编解码器：\1 - 已接近 OGV 工作流"),
        (r"Source audio codec: (.+?) - efficient web-oriented audio", r"源音频编解码器：\1 - 高效的 Web 音频格式"),
        (r"Source audio codec: (.+?) - common compressed audio", r"源音频编解码器：\1 - 常见压缩音频"),
        (r"Source audio codec: (.+?) - uncompressed or near-uncompressed audio", r"源音频编解码器：\1 - 未压缩或接近未压缩音频"),
        (r"Source audio codec: (.+)", r"源音频编解码器：\1"),
        (r"Source codec \((.+?)\) is already OGV-compatible for Love2D", r"源编解码器（\1）已兼容 Love2D 的 OGV"),
        (r"Converting from (.+?) to OGV is recommended for Love2D compatibility", r"为兼容 Love2D，建议从 \1 转换为 OGV"),
    ),
}

RECOMMENDATIONS_ES_REPLACEMENTS.update({
    "Use 'Ideal Loop' only when seamless repetition matters more than file size": "Usa 'Ideal Loop' solo cuando la repetición fluida importe más que el tamaño del archivo",
    "Start with 'Official Godot'; use 'High Compression' only if file size matters more than quick seeking": "Empieza con 'Official Godot'; usa 'High Compression' solo si el tamaño importa más que los saltos rápidos",
    "Use 'Mobile Optimized' for steadier playback, or 'High Compression' if size is the main concern": "Usa 'Mobile Optimized' para una reproducción más estable, o 'High Compression' si el tamaño es la prioridad",
    "Avoid 'Ideal Loop' on long videos unless the clip is very short and truly loop-focused": "Evita 'Ideal Loop' en videos largos salvo que el clip sea muy corto y realmente pensado para repetirse",
    "For longer clips, prefer 'Official Godot', 'Mobile Optimized', or 'High Compression' before trying 'Ideal Loop'": "Para clips largos, prefiere 'Official Godot', 'Mobile Optimized' o 'High Compression' antes de probar 'Ideal Loop'",
    "Use 'Ideal Loop' only when the clip is short and the repeat must feel seamless": "Usa 'Ideal Loop' solo cuando el clip sea corto y la repetición deba sentirse fluida",
    "Start with 'Love2D Compatibility' or 'Lightweight' before trying more aggressive loop settings": "Empieza con 'Love2D Compatibility' o 'Lightweight' antes de probar ajustes de loop más agresivos",
    "Avoid 'Ideal Loop' on longer Love2D clips unless the video is a short decorative loop": "Evita 'Ideal Loop' en clips largos de Love2D salvo que el video sea un loop decorativo corto",
})

RECOMMENDATIONS_FR_REPLACEMENTS.update({
    "Use 'Ideal Loop' only when seamless repetition matters more than file size": "Utilisez 'Ideal Loop' seulement quand la fluidité de la boucle compte plus que la taille du fichier",
    "Start with 'Official Godot'; use 'High Compression' only if file size matters more than quick seeking": "Commencez par 'Official Godot' ; utilisez 'High Compression' seulement si la taille compte plus que l'accès rapide",
    "Use 'Mobile Optimized' for steadier playback, or 'High Compression' if size is the main concern": "Utilisez 'Mobile Optimized' pour une lecture plus stable, ou 'High Compression' si la taille est la priorité",
    "Avoid 'Ideal Loop' on long videos unless the clip is very short and truly loop-focused": "Évitez 'Ideal Loop' sur les longues vidéos sauf si le clip est très court et vraiment pensé pour la boucle",
    "For longer clips, prefer 'Official Godot', 'Mobile Optimized', or 'High Compression' before trying 'Ideal Loop'": "Pour les clips plus longs, préférez 'Official Godot', 'Mobile Optimized' ou 'High Compression' avant d'essayer 'Ideal Loop'",
    "Use 'Ideal Loop' only when the clip is short and the repeat must feel seamless": "Utilisez 'Ideal Loop' seulement quand le clip est court et que la boucle doit paraître fluide",
    "Start with 'Love2D Compatibility' or 'Lightweight' before trying more aggressive loop settings": "Commencez par 'Love2D Compatibility' ou 'Lightweight' avant d'essayer des réglages de boucle plus agressifs",
    "Avoid 'Ideal Loop' on longer Love2D clips unless the video is a short decorative loop": "Évitez 'Ideal Loop' sur les clips Love2D longs sauf si la vidéo est une courte boucle décorative",
})

RECOMMENDATIONS_DE_REPLACEMENTS.update({
    "Use 'Ideal Loop' only when seamless repetition matters more than file size": "Verwende 'Ideal Loop' nur, wenn eine nahtlose Wiederholung wichtiger ist als die Dateigröße",
    "Start with 'Official Godot'; use 'High Compression' only if file size matters more than quick seeking": "Beginne mit 'Official Godot'; nutze 'High Compression' nur, wenn die Dateigröße wichtiger ist als schnelles Springen",
    "Use 'Mobile Optimized' for steadier playback, or 'High Compression' if size is the main concern": "Verwende 'Mobile Optimized' für stabilere Wiedergabe oder 'High Compression', wenn die Dateigröße am wichtigsten ist",
    "Avoid 'Ideal Loop' on long videos unless the clip is very short and truly loop-focused": "Vermeide 'Ideal Loop' bei langen Videos, außer der Clip ist sehr kurz und wirklich für eine Schleife gedacht",
    "For longer clips, prefer 'Official Godot', 'Mobile Optimized', or 'High Compression' before trying 'Ideal Loop'": "Bei längeren Clips solltest du vor 'Ideal Loop' eher 'Official Godot', 'Mobile Optimized' oder 'High Compression' verwenden",
    "Use 'Ideal Loop' only when the clip is short and the repeat must feel seamless": "Verwende 'Ideal Loop' nur, wenn der Clip kurz ist und die Wiederholung nahtlos wirken soll",
    "Start with 'Love2D Compatibility' or 'Lightweight' before trying more aggressive loop settings": "Beginne mit 'Love2D Compatibility' oder 'Lightweight', bevor du aggressivere Schleifen-Einstellungen ausprobierst",
    "Avoid 'Ideal Loop' on longer Love2D clips unless the video is a short decorative loop": "Vermeide 'Ideal Loop' bei längeren Love2D-Clips, außer das Video ist eine kurze dekorative Schleife",
})

RECOMMENDATION_PROFILES = {
    "de": RecommendationProfile(RECOMMENDATIONS_DE_REPLACEMENTS, _RECOMMENDATION_REGEX_RULES["de"]),
    "fr": RecommendationProfile(RECOMMENDATIONS_FR_REPLACEMENTS, _RECOMMENDATION_REGEX_RULES["fr"]),
    "es": RecommendationProfile(RECOMMENDATIONS_ES_REPLACEMENTS, _RECOMMENDATION_REGEX_RULES["es"]),
    "zh_CN": RecommendationProfile(RECOMMENDATIONS_ZH_CN_REPLACEMENTS, _RECOMMENDATION_REGEX_RULES["zh_CN"]),
}
